version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
      interval: "weekly"

- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: "weekly"
  open-pull-requests-limit: 10
  groups:
    kustomize:
      patterns:
        - "go.mod"

- package-ecosystem: gomod
  directory: "kyaml/"
  schedule:
    interval: "weekly"
  open-pull-requests-limit: 10
  groups:
    kyaml:
      patterns:
        - "go.mod"

- package-ecosystem: gomod
  directory: "cmd/config/"
  schedule:
    interval: "weekly"
  open-pull-requests-limit: 10
  groups:
    cmd/config:
      patterns:
        - "go.mod"

- package-ecosystem: gomod
  directory: "api/"
  schedule:
    interval: "weekly"
  open-pull-requests-limit: 10
  groups:
    api:
      patterns:
        - "go.mod"