name: release-kustomize

on: 
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        description: release type (major, minor, or patch).
        options:
          - major
          - minor
          - patch
        required: true
        default: 'patch'
      release_branch:
        type: string
        description: release branch name "release-kustomize-v*"
        required: true
        default: 'master'

jobs:
  pre-build: 
    name: Pre-build
    runs-on: ubuntu-latest
    steps:
      - name: Fetch changes
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.release_branch }}
      - name: Unit test
        id: unit_test
        working-directory: $GITHUB_WORKSPACE
        run: |
          echo "Executing unit test"
          make test-unit-all >> "${GITHUB_OUTPUT}"
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install local tools
        working-directory: $GITHUB_WORKSPACE
        run: |
          make install-local-tools
      - name: Pin kyaml, cmd/config, and api
        working-directory: $GITHUB_WORKSPACE
        run: |
          gorepomod pin kyaml --local --doIt
          gorepomod pin cmd/config --local --doIt
          gorepomod pin api --local --doIt
      - name: Build test
        working-directory: $GITHUB_WORKSPACE
        run: |
          make build-kustomize-api
  e2e-test:
    name: End-to-end Testing
    runs-on: ubuntu-latest
    steps:
      - name: End-to-end testing
        id: e2e_test
        working-directory: $GITHUB_WORKSPACE
        run: |
          make verify-kustomize-e2e
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Release kyaml
        working-directory: $GITHUB_WORKSPACE
        run: |
          make install-local-tools
          gorepomod release kustomize ${{ inputs.release_type }} --doIt
