name: release-api

on: 
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        description: release type (major, minor, or patch).
        options:
          - major
          - minor
          - patch
        required: true
        default: 'patch'
      release_branch:
        type: string
        description: release branch name "release-api-v*"
        required: true
        default: 'master'

jobs:
  pre-build: 
    name: Pre-build
    runs-on: ubuntu-latest
    steps:
      - name: Fetch changes
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.release_branch }}
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version-file: go.work
      - name: Unit test
        id: unit_test
        working-directory: $GITHUB_WORKSPACE
        run: |
          echo "Executing unit test"
          make test-unit-all >> "${GITHUB_OUTPUT}"
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: pre-build
    steps:
      - name: Fetch changes
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.release_branch }}
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version-file: go.work
      - name: Install local tools
        run: |
          make install-local-tools
      - name: Pin kyaml, cmd/config
        run: |

          # Prepare git
          git config --global user.email "development@kustomize.io"
          git config --global user.name "Development"
          git remote add upstream "https://x-access-token:${GITHUB_TOKEN}@github.com/antoooks/kustomize.git"
          git remote -v 
          
          # Pin dependencies: kyaml, cmd/config
          gorepomod pin kyaml --local --doIt
          gorepomod pin cmd/config --local --doIt
      - name: Build api
        run: |
          make build-kustomize-api
      - name: Commit pinned dependencies
        run: |

          # Commit pinned dependencies and handle no commit          
          git add --all
          git commit -m "pin kyaml, cmd/config" || true
          git push
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Fetch changes
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.release_branch }}
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version-file: go.work
          cache-dependency-path: "**/*.sum"
      - name: Pin kyaml, cmd/config
        run: |

          # Prepare git
          git config --global user.email "development@kustomize.io"
          git config --global user.name "Development"
          git remote add upstream "https://x-access-token:${GITHUB_TOKEN}@github.com/antoooks/kustomize.git"
          git remote -v 
          
          # Pin dependencies: kyaml, cmd/config
          gorepomod pin kyaml --local --doIt
          gorepomod pin cmd/config --local --doIt
      - name: Release api
        run: |

          # Prepare git
          git config --global user.email "development@kustomize.io"
          git config --global user.name "Development"
          
          # Release api
          make install-local-tools
          gorepomod release api ${{ inputs.release_type }} --local --doIt
