name: release-kyaml

on: 
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        description: release type (major, minor, or patch).
        options:
          - major
          - minor
          - patch
        required: true
        default: 'patch'
      release_branch:
        type: string
        description: release branch name "release-kyaml-v*"
        required: true
        default: 'master'

jobs:
  pre-build: 
    name: Pre-build
    runs-on: ubuntu-latest
    steps:
      - name: Fetch changes
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.release_branch }}
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version-file: go.work
          cache-dependency-path: "**/*.sum"
      - name: Unit test
        id: unit_test
        run: |
          echo "Executing unit test"
          go install github.com/jstemmer/go-junit-report@latest
          make test-unit-all | go-junit-report -set-exit-code > report.xml
      - name: Test Summary
        uses: test-summary/action@v1
        with:
          paths: |
            ./report.xml
        if: always()
  build:
    name: Build
    needs: pre-build
    runs-on: ubuntu-latest
    steps:
      - name: Fetch changes
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.release_branch }}
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version-file: go.work
          cache-dependency-path: "**/*.sum"
      - name: Build test
        run: |
          make build-kustomize-api
  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Fetch changes
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.release_branch }}
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version-file: go.work
          cache-dependency-path: "**/*.sum"
      - name: Create release changelog
        run: |

          # Prepare git
          git config --global user.email "development@kustomize.io"
          git config --global user.name "Development"
          ./releasing/compile-changelog.sh kyaml HEAD
      - name: Release kyaml
        run: |

          # Release kyaml
          make install-tools
          gorepomod release kyaml ${{ inputs.release_type }} --local --doIt
